### ISSUE TITLE
Change meta og:Image and Twitter:image Given Pages

### ISSUE THREAD

**Issue by SourabhEstuary** [estuary/marketing-site#395]
**Current Status**
Currently we are using Estuary logo for preview image on all social channels.

**Requirement**
update meta Og:Image and Twitter:image for below-given pages:

### Future PR (`open_graph_image` added via https://github.com/estuary/strapi-admin/pull/14)
- [ ] https://estuary.dev/vs-fivetran/
Add this image: https://estuary.dev/static/c1f82a30997106309b458c1cc8b05fb1/a1729/fivetranvestuary3_1_9eba281eac.webp

- [ ] ~https://estuary.dev/vs-airbyte/~
~Add this image:~
~https://estuary.dev/static/886e3a65dce4bef66f4ecb74d4debde8/719cf/Group_22561_d679a10970.webp~

**Best recommended size for OG:image and Twitter:image :1200x630** 

### Completed https://github.com/estuary/marketing-site/pull/398
- [x] https://estuary.dev/
Add this image: https://estuary.dev/static/078d75f95a6a1f1f2b01bbb7ef6aa6d8/a0375/flow-desktop.webp

- [x] https://estuary.dev/product/
Add this image: https://estuary.dev/static/4b50c1031e04dcfc3d4166f32c787d36/ffa0c/real-time-graphic.webp

- [x] https://estuary.dev/pricing/
Add this image: https://estuary.dev/static/1699becc9a7cfb450f7e2fa4f094b50a/c7a5c/graphic_parent.webp

**Comment by travjenkins** [comment]
For the `vs` pages we'll need to add this to Strapi as those are auto generated.

**Comment by travjenkins** [comment]
@altitude-lucas - I opened this up this morning https://github.com/estuary/strapi-admin/pull/14

After Joseph is back he can review and then deploy the changes to Strapi.

**Comment by travjenkins** [comment]
Closing - we have completed everything that we need/can for now.

The compare pages are changing with https://github.com/estuary/marketing-site/issues/457
